"""empty message

Revision ID: 32827e411710
Revises: 377cf86f64d6
Create Date: 2019-11-09 15:39:18.508369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32827e411710'
down_revision = '377cf86f64d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_extension')
    op.drop_table('file_type')
    op.add_column('file', sa.Column('extension', sa.String(length=5), nullable=True))
    op.add_column('file', sa.Column('path', sa.String(length=120), nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'file_extension_id')
    op.drop_column('file', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('url', sa.VARCHAR(length=120), nullable=True))
    op.add_column('file', sa.Column('file_extension_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'file', 'file_extension', ['file_extension_id'], ['id'])
    op.drop_column('file', 'path')
    op.drop_column('file', 'extension')
    op.create_table('file_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file_extension',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=7), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_type_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['file_type_id'], ['file_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
